name: 'Dokploy Deployment'
description: 'Trigger a Dokploy deployment'
branding:
  icon: 'upload-cloud'
  color: 'gray-dark'
inputs:
  dokploy_url:
    description: 'Dokploy base URL, e.g. https://dokploy.example.com'
    required: true
  auth_token:
    description: 'Dokploy authentication token'
    required: true
  application_id:
    description: 'Dokploy application ID'
    required: true
  application_name:
    description: 'Dokploy application name'
    required: true
  wait_for_completion:
    description: 'Wait for deployment to finish (default: false)'
    required: false
    default: 'false'
  restart:
    description: 'Restart application after deployment (default: false)'
    required: false
    default: 'false'
  debug:
    description: 'Enable debug logging (default: false)'
    required: false
    default: 'false'
  skip_deploy:
    description: 'Skip deployment trigger (for testing, default: false)'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: ${{ github.action_path }}/requirements.txt

    - name: Install dependencies
      shell: bash
      run: |
        pip install -q -r ${{ github.action_path }}/requirements.txt

    - name: Run Dokploy deployment
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        INPUT_DOKPLOY_URL: ${{ inputs.dokploy_url }}
        INPUT_AUTH_TOKEN: ${{ inputs.auth_token }}
        INPUT_APPLICATION_ID: ${{ inputs.application_id }}
        INPUT_APPLICATION_NAME: ${{ inputs.application_name }}
        INPUT_WAIT_FOR_COMPLETION: ${{ inputs.wait_for_completion }}
        INPUT_RESTART: ${{ inputs.restart || 'false' }}
        INPUT_SKIP_DEPLOY: ${{ inputs.skip_deploy || 'false' }}
        INPUT_DEBUG: ${{ inputs.debug || 'false' }}
      run: |
        python3 -m src.deploy
